pipeline {
    agent any
    stages {
        stage('Ejecutar script Python') {
            steps {
                // Reemplaza la ruta del script según sea necesario
                sh 'python C:\\Users\\erlin\\OneDrive\\Escritorio\\Programas\\programas\\programas_test\\bot_geshin\\sesion_day_v3.py'
            }
        }
    }
}
