pipeline {
    agent any
    stages {
        stage('Hello') {
            steps {
                script {
                    echo 'Hola, mundo!'
                }
            }
        }
    }
    options {
        skipDefaultCheckout()
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                              branches: [[name: 'main']],
                              userRemoteConfigs: [[url: 'https://github.com/ErlingSteve/Test_Jenkins/tree/main']]])
                }
            }
        }
    }
}
